### ISSUE TITLE
Item pickup bug

### ISSUE THREAD

**Issue by mfb-fake** [yohjimane/xray-16#11]
**Describe the bug**
When trying to pickup items, it's possible that they won't be picked up in your inventory at all, but the animation will show that it's being picked up.

**To Reproduce**
1. Find any items on the ground or at a table.

**Expected behavior**
This bug is more consistent when you're trying to pick stuff up from a elevated surface and not really an issue when trying to pickup items from the ground. Once this bug happens, you won't pick up any items at all, but the animation will show that you did.

**Screenshots**
![Screenshot 2024-04-02 083044](https://github.com/yohjimane/xray-16/assets/94538048/ed85ef78-e539-4364-9e45-e19d13eda8c5)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - OpenXRay Gunslinger build version 9185. Hotfix 0.2.

**Comment by yohjimane** [comment]
Maybe fixed with hotfix v0.0.4, please check it again!

**Comment by mfb-fake** [comment]
> Maybe fixed with hotfix v0.0.4, please check it again!

Nope, this still happens, even with hotfix v0.0.6.
Here's the report log:
[OpenXRay_error_report_240403-083921.zip](https://github.com/yohjimane/xray-16/files/14847880/OpenXRay_error_report_240403-083921.zip)

**Comment by tiltedcan** [comment]
I was having this issue still with the newest hotfix v0.0.9, out of curiosity and convenience I increased the pickup radius and it seems to have mostly remedied the issue. I still get the occasional failed pickup but it's the exception rather than the rule after the pickup radius increase

**Comment by tiltedcan** [comment]
updating this, after more testing there is definitely still a prevalent issue when it comes to items being picked up off of elevated surfaces as noted in silvers initial report

**Comment by Nestandart5443** [comment]
Sorry if I misunderstand something.
But I think that in the selection algorithm you first need to make sure that the item is taken, remove it, and only then play the animation. Because it happens that you can’t reach an object when pressing F, it seems to play the animation earlier than necessary.

sry for bad english

**Comment by tiltedcan** [comment]
Item pickup issues have been mostly solved, some adjustments may be a good idea for model rotation when anchored to actor hands, but this is probably time consuming tedious work and not particularly high prio, happy to give it a crack if someone would like me to. Otherwise this issue can be safely closed for now and we can monitor for regression.

**Comment by yohjimane** [comment]
Adjusting offsets for each item is a separate task, it might be a good one for you to pick up @tiltedcan. Closing this bug out for now.
